package org.firstinspires.ftc.pedroext.tuning;

/**
 * The measured, voltage-normalized dynamics constants produced by the
 * self-calibration harness: max forward/lateral velocities and forward/lateral
 * zero-power (coast) accelerations, plus how many runs were averaged. Immutable.
 */
public final class CalibrationResult {

    private final double xVelocity;                      // in/s
    private final double yVelocity;                      // in/s
    private final double forwardZeroPowerAcceleration;   // in/s^2 (negative)
    private final double lateralZeroPowerAcceleration;   // in/s^2 (negative)
    private final int runCount;

    public CalibrationResult(double xVelocity, double yVelocity, double forwardZeroPowerAcceleration,
                             double lateralZeroPowerAcceleration, int runCount) {
        this.xVelocity = xVelocity;
        this.yVelocity = yVelocity;
        this.forwardZeroPowerAcceleration = forwardZeroPowerAcceleration;
        this.lateralZeroPowerAcceleration = lateralZeroPowerAcceleration;
        this.runCount = runCount;
    }

    public double getXVelocity() { return xVelocity; }
    public double getYVelocity() { return yVelocity; }
    public double getForwardZeroPowerAcceleration() { return forwardZeroPowerAcceleration; }
    public double getLateralZeroPowerAcceleration() { return lateralZeroPowerAcceleration; }
    public int getRunCount() { return runCount; }

    /** A ready-to-paste snippet for the team's Constants (no hand-transcribing of numbers). */
    public String toConstantsSnippet() {
        return "// generated by SelfCalibrationOpMode (" + runCount + " runs, outliers rejected)\n"
                + "followerConstants\n"
                + "    .forwardZeroPowerAcceleration(" + forwardZeroPowerAcceleration + ")\n"
                + "    .lateralZeroPowerAcceleration(" + lateralZeroPowerAcceleration + ");\n"
                + "driveConstants\n"
                + "    .xVelocity(" + xVelocity + ")\n"
                + "    .yVelocity(" + yVelocity + ");";
    }

    @Override
    public String toString() {
        return "CalibrationResult{xVelocity=" + xVelocity + ", yVelocity=" + yVelocity
                + ", forwardZPA=" + forwardZeroPowerAcceleration + ", lateralZPA=" + lateralZeroPowerAcceleration
                + ", runs=" + runCount + "}";
    }
}
